[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "flamer"
description = "A collection of well-developed PyTorch deep learning modules."
authors = [{ name="Taha Shieenavaz", email="tahashieenavaz@gmail.com" }]
urls = { Homepage="https://github.com/tahashieenavaz/flamer" }
keywords = ["modules", "reusable", "deep learning", "machine learning"]
dependencies = ["torch"]

dynamic = ["version"] 
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]

[tool.setuptools_scm] 

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
"*" = ["*.md", "*.txt"]