[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "flamer"
version = "0.0.01"
authors = [
  { name="Taha Shieenavaz", email="tahashieenavaz@gmail.com" },
]
description = "A collection of well-designed PyTorch modules."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["torch"]
keywords = ["deep learning", "pytorch", "modules"]
license = { file = "LICENSE" }
urls = { Homepage="https://github.com/tahashieenavaz/flamer", Repository="https://github.com/tahashieenavaz/flamer", Documentation="https://github.com/tahashieenavaz/flamer#readme" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*", "docs*", "figures*", "mermaid*", "scripts*"]

[tool.setuptools.package-data]
flamer = ["*.md", "*.txt", "*.png"]
